### ISSUE TITLE
BarcodeScanner does not release resources in `5.read-video-vue`

### ISSUE THREAD

**Issue by mattcollier** [Dynamsoft/barcode-reader-javascript-samples#13]
I've made the following simple modifications to the example to demonstrate the behavior here:

https://github.com/Dynamsoft/barcode-reader-javascript-samples/compare/master...digitalbazaar:toggle-scanner?expand=1

By repeating the following steps 5-10 times one can produce the attached performance profile that shows ever increasing resource consumption.

1. Scan barcode (image upload is good for demo)
2. Hit the "TOGGLE SCANNER" button
3. Forcefully run garbage collection using the dev tools
4. Hit the "TOGGLE SCANNER" button
5. Repeat 5-10 times

![Screenshot from 2022-03-23 18-36-18](https://user-images.githubusercontent.com/902041/159810737-a50b3f20-a939-4606-9dee-865c28ae473e.png)

**Comment by Keillion** [comment]
You are right, there is a bug in the sample. I will do a quick fix soon. in 30 mins.

**Comment by Keillion** [comment]
Fixed.

Main change:
```js
const reader = await (this.pReader = BarcodeReader.createInstance());
```
to
```js
const reader = await (this.pReader = this.pReader || BarcodeReader.createInstance());
```

**Comment by Keillion** [comment]
After some test, we find it does have memory leak when `BarcodeScanner.createInstance()`.

We need to do more research. We may need a few days.

You can temporarily walkaround the problem with a singleton scanner.

**Comment by Keillion** [comment]
It's a bug in SDK. We have fixed it in [dynamsoft barcode reader javascript 9.0](https://github.com/Dynamsoft/barcode-reader-javascript).

**Comment by Keillion** [comment]
The vue sample has been updated to 9.0.

**Comment by mattcollier** [comment]
Thank you, the profile looks much better.

![Screenshot from 2022-03-24 09-33-37](https://user-images.githubusercontent.com/902041/159927807-f78d407a-2cb5-4cc0-b78a-ebcd789f44f7.png)
