### ISSUE TITLE
Broken links on sample readme page

### ISSUE THREAD

**Issue by Tom-Dynamsoft** [Dynamsoft/barcode-reader-javascript-samples#195]
On this page https://github.com/Dynamsoft/barcode-reader-javascript-samples/blob/main/README.md

The following links are broken

![image](https://github.com/Dynamsoft/barcode-reader-javascript-samples/assets/12044551/c9a3efe0-826e-47e8-b922-858a1f93cd2a)

**Comment by felixindynamsoft** [comment]
We should also add the link for `Locate-an-item-via-barcode` sample, and update the link for that sample on `https://github.com/Dynamsoft/barcode-reader-javascript-samples/blob/main/use-case/README.md`
